___
# Atividade: Variáveis aleatórias discretas
___

## Aula 09

<div id="indice"></div>

## Índice

- [Corretora de Seguros](#corretora-de-seguros)
    - [Exercício 1](#ex1)
    - [Exercício 2](#ex2)
    - [Exercício 3](#ex3)
    - [Exercício 4](#ex4)
    - [Exercício 5](#ex5)
    - [Exercício 6](#ex6)


In [50]:
import numpy as np
import random
import pandas as pd
from statistics import harmonic_mean

___

<div id="corretora-de-seguros"></div>

## Corretora de Seguros

Uma corretora de seguros paga uma comissão de R\\$50,00 a cada novo seguro que um corretor vende. A probabilidade de um cliente adquirir o seguro é de 0,20. 

1. Descreva como pode se comportar a comissão se um corretor ao abordar 2 clientes de maneira independente um do outro.
1. Qual a probabilidade de um corretor ganhar apenas R\\$50,00?

Vamos considerar os eventos:

- $S_i$: o cliente $i$ compra o seguro;
- $N_i = S_i^C$: o cliente $i$ não compra o seguro.

Pelo enunciado sabemos que:

- $P(S_i) = 0.2$
- $P(N_i) = P(S_i^C) = 1 - P(S_i) = 0.8$

Listando todas as possíveis combinações de eventos, temos:

Cliente 1 | Cliente 2 | Probabilidade           | Valor da comissão
--------- | --------- | ----------------------- | -----------------
$N_1$     | $N_2$     | $P(N_1)P(N_2)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2)$ = $0.16$ | 50
$S_1$     | $N_2$     | $P(S_1)P(N_2)$ = $0.16$ | 50
$S_1$     | $S_2$     | $P(S_1)P(S_2)$ = $0.04$ | 100

Estamos interessados no valor da comissão de um corretor. Para isso, vamos definir a variável aleatória:

- $C$: valor da comissão do corretor.

Assim, o item 2 pode ser interpretado como: qual é o valor de $P(C=50)$?

Consultando a tabela calculada acima, vemos que $P(C=50) = 0.16 + 0.16 = 0.32$.

<div id="ex1"></div>

### EXERCÍCIO 1

Calcule o valor esperado e a variância da variável $C$.

*Resposta esperada para esperança e variância respectivamente: 20.0 reais ; 800.0 reais^2*

In [51]:
# ESCREVA SEU CÓDIGO AQUI
med = 0.64*0 + 0.32*50 + 0.04*100
med

20.0

In [52]:
var = ( 64*(0-med)**2 + 32*(50-med)**2 + 4*(100-med)**2 )/100
var

800.0

___
## Tomando uma decisão

Imagine que a corretora de seguros irá fornecer um aumento na comissão dos corretores. Entretanto, cada corretor poderá escolher uma das seguintes opções:

- **Opção 1:** Nova comissão será a comissão atual mais um fixo de R$ 20,00;
- **Opção 2:** Nova comissão será o dobro da atual comissão.

<br>

A ideia aqui é fazer uma escolha de qual delas é melhor para aumentar o ganho de um corretor. 

Para isso, resolva os exercícios a seguir para auxiliá-lo nessa escolha.

<div id="ex2"></div>

### EXERCÍCIO 2

Construa a distribuição de probabilidade para cada uma das opções.


ESCREVA SUA RESPOSTA AQUI

# PROF


   Probabilidade        | Fixo de R\\$ 20,00 | Dobro da comissão atual
----------------------- | ------------------ | -----------------------
$P(N_1)P(N_2)$ = $0.64$ | 20                 | 0
$P(N_1)P(S_2)$+$P(S_1)P(N_2)$ = $0.32$ | 70                 | 100
$P(S_1)P(S_2)$ = $0.04$ | 120                | 200


<div id="ex3"></div>

### EXERCÍCIO 3

Considerando as respectivas distribuições de probabilidades, calcule o valor esperado e a variância para cada opção. 

In [53]:
med1 = (0.64*0 + 0.32*50 + 0.04*100)+20
med1

40.0

In [54]:
var1 = ( 64*(20-med1)**2 + 32*(70-med1)**2 + 4*(120-med1)**2 )/100
var1

800.0

In [55]:
med2 = (0.64*0 + 0.32*50 + 0.04*100)*2
med2

40.0

In [56]:
var2 = ( 64*(0-med2)**2 + 32*(100-med2)**2 + 4*(200-med2)**2 )/100
var2

3200.0

<div id="ex4"></div>

### EXERCÍCIO 4

Baseado nas propriedades da esperança (nos slides), calcule o valor esperado para a nova comissão em cada uma das opções.

*Resposta esperada para esperança opção 1 e 2 respectivamente: 40.0 reais ; 40.0 reais*

In [57]:
# harmonic_mean([0,100,200], weights=[64,32,4])
# harmonic_mean([40, 60], )

esperanca1 = ( 64*(0+20) + 32*(50+20) + 4*(100+20))/100
esperanca1

40.0

In [58]:
esperanca2 = ( 64*(0) + 32*(100) + 4*(200))/100
esperanca2

40.0

<div id="ex5"></div>

### EXERCÍCIO 5

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 3200.0 reais^2*

In [59]:
var1 = ( 64*(20-med1)**2 + 32*(70-med1)**2 + 4*(120-med1)**2 )/100
var1

800.0

In [60]:
var2 = ( 64*(0-med2)**2 + 32*(100-med2)**2 + 4*(200-med2)**2 )/100
var2

3200.0

<div id="ex6"></div>

### EXERCÍCIO 6

Baseado nos resultados acima, qual opção você recomendaria para um corretor?

opção um pois tem o mesmo ganho em média, mas com maior estabilidade.

# Referências

1. MONTGOMERY, D. et al. Estatística Aplicada e Probabilidade para Engenheiros. 6. ed. Seções 2.8 e 3.1
1. MAGALHÃES, M. et al. Noções de Probabilidade e Estatística. 7. ed. Seções 3.1 e definições 4.2 (p. 110) e 4.5 (p. 121)